title: Yaqian Zhang
description: Research Assistant Professor,\
Shanghai Jiao Tong University
#Ph.D. Candidate, Nanyang Technological University (NTU)
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
